// var mod1 = require('./module1.js');
// var mod2 = require('./module2.js');
// var mod3 = require('./module3.js');
// var mod4 = require('./module4.js');
var mod5 = require("./module5").fn2;
// console.log(mod1);
// console.log(mod2);
// console.log(mod3);
// console.log(mod4);
console.log(mod5);
